spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devbanck?useSSL=false
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: or.hibernate.dialectMySQL5Dialect
    